### ISSUE TITLE
Get Issue at building VRPN library

### ISSUE THREAD

**Issue by EvilOfGlass** [PjotrSvetachov/VRPNInput#1]
I was building vrpn on windows. After I uncheck almost everything and then generate the file. I build the  library with visual studio 2013. I can't find any directory call include or lib.
Am I wrong at one of the steps?

**Comment by PjotrSvetachov** [comment]
In cmake you need to set hte CMAKE_INSTALL_PREFIX to the folder you want the include and lib files to becopied. Then you need to build the INSTALL project in the solution that cmake generates.

**Comment by EvilOfGlass** [comment]
I generate the include and lib directory now. But I still not clear abhout how to use this plugin.(I am a newbee,sorry~) When I start the editor,the warning " module 'VRPNInput' can't be found " show up. So I want to know more about other details.

Where the VRPN.build.cs file come from? Is it the same file as VRPNInput.build.cs ?
My folder end up like this:
![baidu ime_2015-12-8_20-59-56](https://cloud.githubusercontent.com/assets/6783721/11656283/0eab0b76-9def-11e5-98e2-0d09721b32d6.jpg)
and 
![baidu ime_2015-12-8_21-0-35](https://cloud.githubusercontent.com/assets/6783721/11656345/77cdbc20-9def-11e5-8ddc-92d013aaaa17.jpg)

But I think the plugin may end up like this:
![baidu ime_2015-12-8_21-2-10](https://cloud.githubusercontent.com/assets/6783721/11656364/9712a6e0-9def-11e5-8db9-a7fb011f2bd3.jpg)

**Comment by PjotrSvetachov** [comment]
the VRPN.build.cs file can be gotton from VRPN.rar here: https://github.com/PjotrSvetachov/VRPNInput/releases

**Comment by PjotrSvetachov** [comment]
As of now the file is also added to the github repository.
