### ISSUE TITLE
Build Engine with the plugin

### ISSUE THREAD

**Issue by jimmynex** [PjotrSvetachov/VRPNInput#2]
Hi,
I'm currently having an issue for the engine building with the plugin.
"Erreur C2259   'VRPNTrackerInputDevice' : impossible d'instancier une classe abstraite    UE4 C:\Users\NEX\Documents\GitHub\UnrealEngine\Engine\Plugins\HPCV\VRPNInput\Source\VRPNInput\Private\VRPNInputDeviceManager.cpp    100"
Could be translated with : impossible to instantiate an abstract class about that line : 
`InputDevice = new VRPNTrackerInputDevice(*TrackerAdressString, CritSect, bEnabled);`
That cause the fail to produce the UE4Editor-VRPNInput.dll

Thanks for your work.
Jim

**Comment by PjotrSvetachov** [comment]
With which version of visual studio are you compiling? Does it say why it thinks VRPNTrackerInputDevice is an abstract class?

**Comment by jimmynex** [comment]
I'm working with VS 2015.
I guess this method could be the problem : 
`virtual bool GetControllerOrientationAndPosition(const int32 ControllerIndex, [...])`
this is a virtual method, so does this make VRPNTrackerInputDevice an abstract class ?
(line 99 VRPNInputDevice.h)

**Comment by PjotrSvetachov** [comment]
Weird as there are no build problems here with VS2015.
It's a virtual method but it has an implementation. It's for the IMotionController interface. What version of UE4 are you compiling against? I made this plugin for the current released version (4.10).

**Comment by jimmynex** [comment]
I took the Unreal Version on github yesterday, 4.11.0 prev 7 !
I will try another version yes !

**Comment by PjotrSvetachov** [comment]
I looked at the 4.11 version and they seem to add a new virtual method to the IMotionController interface that causes the build error. When they release versions 4.11 I'll look into adding support for it.

**Comment by jimmynex** [comment]
4.10 build worked for me ! =)
I will use openvibe to connect an Epoc BCI to Unreal Engine, is openvibe an already supported device ?
Thank you
Jim

**Comment by PjotrSvetachov** [comment]
Wow that looks cool. For now the plugin can only receive vrpn_Tracker and vrpn_button messages. I have googled to what openvibe is and it looks like that it is also sends vrpn_Analog messages, those are not yet supported as we don't have any devices in our lab that send those. But they should be easy to add.

**Comment by PjotrSvetachov** [comment]
I added the missing method to make it compile with 4.11. In 4.11 they have added a new method that says if a motion controller is tracked or not. For now it will always report as being tracked, in the future I need to see a reliable way to get that information from a vrpn device.
